package OnlineStore;


/**
* OnlineStore/AccountRegistrationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VICTUS/IdeaProjects/untitled14/src/main/resources/account_registration.idl
* Friday, March 7, 2025 1:59:13 PM ICT
*/

public interface AccountRegistrationOperations 
{
  boolean registerAccount (String username, String password, String email);
} // interface AccountRegistrationOperations
