package OnlineStore;

/**
* OnlineStore/AccountRegistrationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/VICTUS/IdeaProjects/untitled14/src/main/resources/account_registration.idl
* Friday, March 7, 2025 1:59:13 PM ICT
*/

public final class AccountRegistrationHolder implements org.omg.CORBA.portable.Streamable
{
  public AccountRegistration value = null;

  public AccountRegistrationHolder ()
  {
  }

  public AccountRegistrationHolder (AccountRegistration initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountRegistrationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountRegistrationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountRegistrationHelper.type ();
  }

}
